### ISSUE TITLE
Gateway node permanently 'offline'

### ISSUE THREAD

**Issue by readeral** [pierrecle/node-red-contrib-mi-devices#32]
Hi pierrecle, I'm unable to bring my gateway online. All is set up well in the app, but retrieving the IP address, SID and key/password still does not enable my hub to be considered 'online'.

Can you advise of any other steps I may have missed in order to bring this device into my node-red?

Thanks,

Al

**Comment by nidayand** [comment]
I had the same issue - I'm running Node-RED in a Docker container but my setup does not work with port mapping for UDP multicast. Instead of mapping only -p 1880:1880 i used --net=host when I started the container.. Are you running it in a container?
E.g.

`docker run -it --net=host --user 1026  -v /volume1/docker/nodered/:/data --name nodered pgnodered:1.0.1`

**Comment by readeral** [comment]
My issue was annoyingly more simple than this... was using on a Raspberry Pi. Although I had reserved the IP address, the gateway must've jumped IP addresses momentarily before I set up the reserved address, and so it was permanently looking in the wrong place for the gateway. Solving that has solved my issue!

**Comment by bemble** [comment]
Hey, sorry for the delay.
Glad @readeral to hear your problem is solved and easilly.
Thanks @nidayand for the tip ;)

**Comment by xbmcnut** [comment]
@nidayand Is the -it required to get NR to work with UDP packets? I'm using docker-compose so not quite sure how to integrate that in.

```
version: '3'
services:

  nodered:
    container_name: nasnodered
    restart: unless-stopped
    image: nodered/node-red-docker
    user: "root"
    # devices:
    #   - /dev/ttyUSB0
    volumes:
      - /volume1/docker/node-red:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1880:1880"
    network_mode: "host"
```
